//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public string ID { get; set; }
        public int State { get; set; }
        public int CardType { get; set; }
        public bool Tarskartya { get; set; }
        public System.DateTime Expiration { get; set; }
    }
}
