//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public System.DateTime DayOfTransaction { get; set; }
        public System.DateTime TimeOfTransaction { get; set; }
        public double Money { get; set; }
        public int Type { get; set; }
        public string CardNumber { get; set; }
        public string Dealer { get; set; }
    }
}
